version: '2'
services:
  postgres:
    image: "postgres:16.3"
    networks:
      - streaming-network
    hostname: postgres_kafka
    container_name: postgres_kafka
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "181093"
      POSTGRES_DB: "kafka_data"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  adminer:
    image: "adminer:4.8.1"
    networks:
      - streaming-network
    hostname: adminer
    container_name: adminer
    ports:
      - "8380:8080"

  kafka-0:
    image: 'confluentinc/cp-kafka:7.6.1'
    networks:
      - streaming-network
    hostname: kafka-0
    container_name: kafka-0
    ports:
      - '9094:9094'
    volumes:
      - "kafka_data_0:/var/lib/kafka/data"
      - "./config/kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093
      - CLUSTER_ID=XMVdmieVScezIPmnB_QcXA
      # Listeners
      - KAFKA_LISTENERS=CONTROLLER://:9093,INTERNAL://:29092,DOCKER_NETWORK://:9092,EXTERNAL://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-0:29092,DOCKER_NETWORK://kafka-0:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER_NETWORK:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Clustering
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
#      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0

      # Server Default Properties
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_NUM_PARTITIONS=3


  akhq:
    image: tchiotludo/akhq:0.24.0
    depends_on:
      - kafka-0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            my-cluster:
              properties:
                bootstrap.servers: "kafka-0:9092"
    ports:
      - "8081:8080"
    networks:
      - streaming-network


networks:
  streaming-network:
    external: true

volumes:
  kafka_data_0:
    driver: local
  postgres_data:
    driver: local